/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useRef, useMemo } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

const Human = forwardRef((props, ref) => {
  const group = useRef()
  const { scene, animations } = useGLTF('/T-transformed.glb')
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  useAnimations(animations, group)

  return (
    <group ref={ref || group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Armature"
          position={[0, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <primitive object={nodes.mixamorigHips} />
        </group>
        <skinnedMesh name="Object_11001" geometry={nodes.Object_11001.geometry} material={materials['material_2.001']} skeleton={nodes.Object_11001.skeleton} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Object_4001" geometry={nodes.Object_4001.geometry} material={materials.material_0} skeleton={nodes.Object_4001.skeleton} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Object_5001" geometry={nodes.Object_5001.geometry} material={materials.material_0} skeleton={nodes.Object_5001.skeleton} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Object_6001" geometry={nodes.Object_6001.geometry} material={materials.material_0} skeleton={nodes.Object_6001.skeleton} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Object_7001" geometry={nodes.Object_7001.geometry} material={materials['material_0.001']} skeleton={nodes.Object_7001.skeleton} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Object_9001" geometry={nodes.Object_9001.geometry} material={materials['material_1.001']} skeleton={nodes.Object_9001.skeleton} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
    </group>
  )
})

export default Human
useGLTF.preload('/T-transformed.glb')
